### PR TITLE
clear_ouput_directory update

### PR DESCRIPTION
**Pull request by blameazu**
generate a random named directory to put resources in
and remove it after compressing
* in clear_output_directory mode only

### CODE REVIEW

**Review by tobiichi3227 — APPROVED** [review]

**Comment by tobiichi3227** [comment]
Do you have any commit not push?
If answer is no, I will merge this PR.

**Comment by blameazu** [comment]
that's all thx u

**Comment by blameazu** [comment]
Btw Linux operation instructions need someone else to update because my system is windows🥲

**Comment by tobiichi3227** [comment]
Linux operation guide just like windows.

**Pull request merged**
